
 const recipes = [{   
        "id": 1,
        "name" : "Lumpia",
        "author": "William Atienza",
        "authorTitle": "Sociology, PhD Candidate",
        "prepTime": "1 hour",
        "cookTime": "30 minutes",
        "servingSize": "5 lumpia",
        "yields": "5 servings",
        "ingredients": [
            "1.5lb ground pork", 
            "2 carrots, grated", 
            "2 sticks of celery, finely chopped", 
            "One yellow onion, finely chopped", 
            "2 cloves garlic, finely chopped", 
            "1 tsp minced fresh ginger",
            "1 tbsp crushed black pepper",
            "2-3 tbsp soy sauce",
            "2 cup canola oil",
            "25 pack spring roll wrapper",
            "A small cup of room temperature water for wrapping"
        ],
        "dippingSauce" : ["Sweet & sour sauce", "Soy sauce to taste", "Minced green serrano pepper White vinegar to taste"],
        "story" : "Born to a Mexican mother and a Filipino father, I grew up feeling more culturally tied to my Mexican heritage and was relatively isolated from my Filipino background. So it was a real treat when my dad cooked for the family because food was one of my only connections to a culture I knew very little about. A favorite dish that I always helped him make was lumpia, a Filipino take on a spring roll. Sitting at the table, my dad and I would stuff and roll one piece at a time, all the while listening to him recount stories about life back in his hometown, and about my grandparents, his kid summers on the farm, jeepneys, the family carabao, and playing in the river catching shrimp with his friends. For me, lumpia was not just a dish: it was something that brought me closer to my Filipino heritage and identity.",
        "contians": ["soy", "wheat"],
        "dietaryRestrictions": "",
        "source": "Family",
        "directions": [
            "01 In a large bowl, add the ground pork, carrots, celery, onion, garlic, and  ginger. Using a fork or hands, combine the ingredients until everything is  well mixed ", 
            "02 Add the black pepper and two tablespoons of soy sauce. Mix well, then bring your nose close to the bowl for a “flavor-sniff-check:” the meat should smell fragrant with the soy sauce and pepper (well-seasoned), but the soy should not be overpowering (over-salted). If needed, add another tablespoon of soy sauce to the bowl and mix well. If unsure, refrain from adding more soy sauce and just use the extra for dipping later. ", 
            "03 Turn on stove to medium setting. In a deep, medium-large frying pan,  heat canola oil to about 300°F. If you don’t have a thermometer, you’ll  know oil is hot when it sizzles and pops if you dip chopsticks into it. ", 
            "04 While waiting for the oil to heat up, begin filling the spring roll wrappers. Take one spring roll wrapper, and set it on a dry surface in a diamond  shape. With a fork, take about 1 ½ tablespoons of mixture and evenly  spread at the bottom half of the wrapper, leaving about 2 inches of space between the mix and the bottom point. Try not to make your lumpia too fat or too skinny. Optional: with a knife, cut lumpia in half. ",
            "05 Fold the bottom point over the filling, then fold in the left and right edges to make an envelope shape. Roll the wrapper towards the top point, using  your fingers to compress the meat as you roll. ",
            "06 Right before you close up the roll, dip your finger in the water, and like  you would when sealing an envelope, wet the edges and seal the roll. ",
            "07 When your oil is hot, using tongs, add lumpia to the pan. Keep about a  half inch of space between rolls in order to ensure even cooking. Note that  if the lumpia is cooking too fast or burning, reduce heat. Fry each side for about 2 - 4 minutes, or until the wrapper starts to turn golden brown. ",
            "08 Remove from heat and place on some paper towels. Wrapper will be  drenched in oil and so will continue to cook, hence why it’s important to  remove from heat before turning golden brown. ",
            "09 Serve with rice, guisado (sauteed vegetables), and/or pansit (Filipino  stir fry noodles). Dip in sweet and sour sauce; or, mix in a small bowl some  soy sauce, white vinegar and minced serrano pepper to your taste. My dad  and I would also sometimes dip our lumpia in ketchup mixed with Tabasco  sauce… Masarap!!"
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 2,
        "name" : "Potato Fires Perkedel",
        "author": "Dian Prasetyawati",
        "authorTitle": "Interdisciplinary Urban Design and Planning, PhD Candidate",
        "prepTime": "40 minutes",
        "cookTime": "20 minutes",
        "servingSize": "4 pieces",
        "yields": "6 servings",
        "ingredients": [
            "½ cup vegetable oil", 
            "½ lb frozen potato fries",
            "½ cup shallot, minced",
            "2 cloves garlic, minced", 
            "¼ lb ground beef", 
            "1 tbsp ground nutmeg", 
            "1 ½ tbsp ground candlenut (or macadamia nuts)", 
            "Salt and pepper to taste 2 eggs"
        ],
        "dippingSauce": "",
        "story" : "As a child, I was raised in a province that serves seafood-based dishes and plenty of grilled, tangy and citrusy spiced food due to my parent’s work in South Sulawesi. Eventually, after several years serving in a remote region, my parents decided they wanted to go back to their hometown. I found it hard to adjust to Javanese sweet-palm sugar or coconut-based mostly- braised cooking food. So ‘perkedel’ is one of the first batches of Javanese traditional foods that I actually liked since the food is neutral and comforting, sweet but not overwhelming, spicy but subdued, and when served along with tumpeng or tangy Soto, it reminds me so much of my childhood home- cooking. I like it so much that I learned how to cook it when I was 11. After years of cooking this recipe with different meat (you can even replace the potato with smashed fried tofu) I also realize that this food uses one of three key recipes of mix spices that are commonly shared by different ethnicities on different Indonesian islands. So although it was originally made to recreate a version of Dutch’s ‘frikadeller’, this food is versatile and every spice in a bite of perkedel will always remind me of home.",
        "contians": ["eggs", "tree nuts"],
        "dietaryRestrictions": "",
        "source": "Mom",
        "directions": [
            "01 Heat 3 tbsps of vegetable oil in a deep skillet. Fry the potato fries according to package directions, and set aside on paper towels to drain. Option to bake potato fries instead of deep-frying ",
            "02 Heat 1 tbsp vegetable oil in a separate pan. Saute shallot and garlic until fragrant. ",
            "03 Add ground beef to shallot and garlic. Season with parsley, nutmeg, candlenut, salt, and pepper. Cook until browned. Set aside and let cool. ",
            "04 Whisk eggs. ",
            "05 Once cooled enough to handle, combine potato fries, cooked ground beef, and 1 whisked egg by hand until uniform in texture. ",
            "06 Form 20-24 rounded meatballs. Dip each meatball in the remaining whisked egg to evenly coat the outer surface. ",
            "07 Heat remaining vegetable oil in a deep skillet. Fry each meatball until golden brown, around 3-5 minutes."
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 3,
        "name" : "Potato Pastry Puffs",
        "author": "Priya Kumar",
        "authorTitle": "Biosafety Officer, Environmental Health & Safety",
        "prepTime": "30 minutes",
        "cookTime": "20 minutes",
        "servingSize": "1 pastry",
        "yields": "4 servings",
        "ingredients": [
            "1 tsp cooking oil",
            "1⁄2 tsp cumin seeds",
            "1 tsp ginger, grated",
            "2 green chillies, crushed",
            "1 onion, finely chopped",
            "Salt to taste",
            "1⁄2 tsp turmeric powder",
            "1⁄4 tsp red chilli powder",
            "2 potatoes, boiled",
            "1 tsp lemon juice",
            "2 sprigs cilantro leaves, finely chopped",
            "Frozen pastry puff sheets"
        ],
        "dippingSauce": "",
        "story" : "In India, when we were children, I remember the bakery man would come in the evenings around 6pm to our neighborhood with freshly made potato pastry puffs to sell. We would wait outside the house and as soon as we would hear the bicycle bell, we would run outside to buy these. These puffs remind me of how we enjoyed this snack as children, and when I saw these pastry sheets at Trader Joe’s, I tried this recipe. It really came out well so I wanted to share it with you. Enjoy as an evening snack with a hot cup of Indian tea.",
        "contians": ["wheat"],
        "dietaryRestrictions": "vegetarian",
        "source": "Self-made",
        "directions": [
            "01 The first step is to prepare the stuffing. Heat a wide, heavy bottom pan on medium heat and add oil. ",
            "02 In hot oil, add cumin seeds, chopped ginger, and green chilies. Saute for about 30 seconds and add chopped onion. ",
            "03 Again saute everything until onion turns translucent. Add salt, turmeric powder, red chilli powder, and mix well. ",
            "04 Stir for 30 seconds and add boiled potatoes. Crush boiled potatoes into small chunks, and mix well. ",
            "05 Turn off the heat, add lemon juice, and chopped cilantro leaves. Mix everything well and the stuffing is ready. ",
            "06 Lay each puff-pastry sheet flat on a lightly floured work surface. Cut the sides using a knife or pizza cutter to make it look like a square/rectangle. ",
            "07 Now take each piece and put 1 tablespoon of potato filling in the center. Lift top right corner and join it with left bottom corner. Seal it completely by pinching the edges together. ",
            "08 Take out a parchment lined baking tray and put the ready to bake puffs onto the tray. Preheat oven to 425°F. Bake it at 425°F for 10-15 minutes. After 15 minutes, the crispy, flaky and puffed up potato patties are ready to be served. ",
            "09 Serve pastry as a tea time snack with a cup of hot masala chai."
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 4,
        "name" : "Papa a la Huancaina",
        "author": "Wesley Howard Benavides de McLain",
        "authorTitle": "Molecular, Cellular, Developmental Biology & Food Systems, Nutrition, and Health BA/BS, 2021",
        "prepTime": "10 minutes",
        "cookTime": "15 minutes",
        "servingSize": "1 plate",
        "yields": "5 servings",
        "ingredients": [
            "4-6 yellow potatoes",
            "1 garlic clove",
            "1⁄2 cup jarred aji Amarillo paste 2 cups cottage cheese or queso fresco",
            "Saltine crackers, for thickening",
            "2 tbsp olive oil",
            "Dash of salt and pepper",
            "4-6 boiled eggs, peeled and sliced lengthwise",
            "Purple or Kalamata olives to taste (optional)",
            "Large lettuce leaves, for garnish and plating"
        ],
        "dippingSauce": "",
        "story" : "Growing up as a Peruvian-American, there was never a family or Peruvian gathering without this staple dish. Papa a la Huancaina is a popular Peruvian appetizer-dish, so it was made readily at many kinds of gatherings, not just Peruvian ones, but even times like Christmas or Thanksgiving! We always mixed up Peruvian cuisine along with the regular American cuisine when I was growing up. This relatively simple dish of potatoes and eggs with a rich creamy cheese and pepper sauce really exemplifies Peruvian cuisine! Not only does it have the unique aji amarillo (yellow pepper) that all Peruvians know well, but the centerpiece is the potato, which is interesting because potatoes originated in the Andes of Peru! I always know I’m among other Peruvians when I see this dish at a gathering, and it brings a sense of welcoming and familiarity to my culture.",
        "contians": ["eggs", "wheat", "milk"],
        "dietaryRestrictions": "vegetarian",
        "source": "Mom",
        "directions": [
            "01 Gather the ingredients; prepare a blender. ",
            "02 Boil 4-6 yellow potatoes until tender. ",
            "03 Put the garlic, aji Amarillo (this can be adjusted depending on how spicy you want it) and cottage cheese in the blender. Blend until smooth. If it is too thin, add 2-3 saltine crackers that are crushed, adjust to have a thicker consistency. ",
            "04 When mixture is smooth, add the olive oil, then salt and pepper to taste. ",
            "05 Prepare the plates with the large lettuce leaves as a base. Slice the boiled potatoes into slices, usually 3-4 slices per plate. ",
            "06 Pour the sauce over the potatoes, making sure to cover it generously. Add the sliced egg on top, followed by the olives (if using)."
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 5,
        "name" : "Poutine",
        "author": "Tiffany He",
        "authorTitle": "Biology, BS, 2021",
        "prepTime": "5 minutes",
        "cookTime": "20 minutes",
        "servingSize": "1 plate",
        "yields": "2 servings",
        "ingredients": [
            "1 bag of store-bought frozen French fries",
            "1 can beef gravy",
            "2 cups cheese curds"
        ],
        "story" : "",
        "dippingSauce": "My family moved to Canada when I was 12. I spent my middle school and high school years in Toronto, and I have tried tons of traditional Canadian food while travelling to Quebec. My favourite dish all the time is poutine. My first time trying poutine was at the cafeteria in middle school. Every weekday, my friends and I waited in line at the school cafeteria, waiting in line to buy our $5 lunch combo, and gathering around the long benches to eat the food. No surprise, poutine was a staple dish there, and due to my long love for fries, I asked for the fries. The lady at the kitchen asked whether I wanted just fries or poutine. I was confused, “What is poutine?” The lady smiled and scooped cheese and gravy onto my fries, and asked me to try it. Ever since that, I fell in love with poutine. It is so simple, yet so delicious.",
        "contians": ["milk"],
        "dietaryRestrictions": "",
        "source": "Self-made",
        "directions": [
            "01 Bake the fries in the oven according to instructions on the bag. ",
            "02 Begin to warm your gravy while the fries are in the oven. ",
            "03 Place the fries on a serving plate, and sprinkle the cheese curds over evenly. ",
            "04 Ladle the hot beef gravy over the fries and cheese, and serve immediately."
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 6,
        "name" : "Ruth’s Okra and Potatoes",
        "author": "Sara Woolcock",
        "authorTitle": "Nutritional Sciences, MPH, 2020",
        "prepTime": "10 minutes",
        "cookTime": "30 minutes",
        "servingSize": "1 cup",
        "yields": "5 servings",
        "ingredients": [
            "2 tbsp olive oil",
            "1 medium onion, diced",
            "1 lb okra, washed and sliced",
            "3 medium red or yellow potatoes, diced in 1-inch cubes",
            "1 clove minced garlic (optional) 1 tsp salt",
            "1⁄2 tsp pepper or to taste"   
        ],
        "dippingSauce": "",
        "story" : "My mom grew up in Georgia, and her favorite Southern food is okra. But my mom has lived most of her adult life in a small town in Western Pennsylvania, where I grew up, and for some reason, it is very difficult to find fresh okra there. The closest place we could find okra was an Indian grocery store about an hour’s drive away. When my mom did make the pilgrimage to buy it, it would be the special dish for dinner that evening. She developed this recipe of okra and potatoes to let us have the classic okra flavor mixed with the comfort of potatoes. Now that I am living in Seattle, there are so many ethnic markets and farmers markets that sell okra, and my mom always cooks this recipe for me when she comes to Seattle to visit. It reminds me of the taste of home.",
        "contians": [],
        "dietaryRestrictions": "vegan",
        "source": "Mom",
        "directions": [
            "01 In a large skillet, heat oil over medium heat. Add onion to skillet and let soften for 1-2 minutes. ",
            "02 Add okra, and let cook for 1-2 minutes. Add potatoes. ",
            "03 Cook potatoes, okra and onion cook in an open skillet until starting to brown, stirring frequently for about 15 minutes. Option to add garlic and stir until fragrant. ",
            "04 Cover by placing lid on top of skillet. Stir every few minutes. ",
            "05 When potatoes reach desired softness (about 10 min), add salt and pepper. Remove from heat. Serve and enjoy!"
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 7,
        "name" : "Tamagoyaki",
        "author": "Sara Clayton",
        "authorTitle": "Human Centered Design & Engineering, MS, 2021",
        "prepTime": "5 minutes",
        "cookTime": "5 minutes",
        "servingSize": "1½ eggs",
        "yields": "2 servings",
        "ingredients": [
            "Three eggs",
            "Vegetable oil for the pan (~2 tbsp) 3 tbsp dashi powder",
            "2 tbsp soy sauce",
            "2 tbsp mirin",
            "1 tbsp sugar",
            "1 tbsp salt"
        ],
        "dippingSauce": "",
        "story" : "The cornerstone of any good bento includes one of my favorite, yet most simple, dishes of all — the humble tamagoyaki. Tamagoyaki is a Japanese rolled omelet that, when done well, is soft and pillowy with just the right amount of umami. The beauty of tamagoyaki is that it tastes good right off the pan or at room temperature in a bento. Having grown up in California as a half-Japanese American, I took for granted the proximity of the Japanese community and food around me there. So when I moved up to Seattle, perhaps as a way to cope with some degree of homesickness, I started making my own bentos. One of the first things I ever made was tamagoyaki for my bento and it is still something I make for my bentos, though I’ve improved my technique quite a lot. I hope you enjoy tamagoyaki just as much as I do.",
        "contians": ["eggs", "wheat", "soy"],
        "dietaryRestrictions": "",
        "source": "Adaoted recipe",
        "directions": [
            "01 Heat a pan over medium heat. ",
            "02 Get a small saucer, and add vegetable oil to it. Cut a paper towel into a triangular shape or any shape that will help spread the oil on the pan. ",
            "03 Once the pan is warm, use chopsticks to grab the paper towel triangle and spread the oil on every inch and corner of the pan. ",
            "04 While the pan is warming up, gather your eggs and all the seasoning. ",
            "05 First, crack the eggs in a bowl and mix. Mix the eggs until it's completely yellow and there aren't any whisps. ",
            "06 Add all seasoning to the egg mixture, then mix until the mixture looks even. ",
            "07 By this point, the pan should have reached medium heat. Slowly pour one third of the egg mixture. The egg mixture should immediately start cooking. ",
            "08 Once the egg layer is nearly cooked through, starting with the side closest to you, start rolling the egg layer onto the other side of the pan. ",
            "09 Before moving the rolled-up egg layer back to the side closest to you, grab the paper towel triangle with your chopsticks and spread the oil around the side closest to you. ",
            "10 Move the rolled up egg back to the side closest to you and spread oil on the other end. ",
            "11 For the second time, when you pour in the next 1/3 of the egg mixture, lift the rolled-up layer so that the egg mixture will move underneath and that, when cooked, the egg mixture will stick to the rolled-up layer. ",
            "12 Repeat steps 8 through 10 until your third egg layer is ready. This time, get a flat surface with a paper towel on it and flip the pan onto it, so that the rolled up egg will be upside-down. ",
            "13 If you have a sushi rolling mat, transfer the rolled egg into this mat and shape it. Let it sit in that shape for five minutes. ",
            "14 Take the rolled egg from the sushi mat, cut into slices, and serve. Itadakimasu!"
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 8,
        "name" : "Japanese Nasu Miso",
        "author": "Emily Sakaida",
        "authorTitle": "Food Systems, Nutrition, and Health, BA, 2021",
        "prepTime": "5 minutes",
        "cookTime": "15 minutes",
        "servingSize": "1⁄2 cup",
        "yields": "6 servings",
        "ingredients": [
            "1 tbsp + 1⁄2 tsp cooking oil for pan 1 tsp minced ginger",
            "2 japanese eggplants, diced",
            "1 green bell pepper, diced",
            "2 tbsp miso",
            "2 tbsp brown sugar",
            "1 tbsp dashi soup base 1 tsp mirin",
            "1⁄4 tsp sesame oil",
            "Green onion, chopped and to taste 1 tsp sesame seeds",
            "Red pepper flakes (optional)"
        ],
        "dippingSauce": ["Japanese Sticky Rice"],
        "story" : "Nasu miso is the comfort of eating with my family at home. It is nostalgia and my mother’s love. This recipe is very special to me because it represents family, and I find that I miss my family and certain home-cooked recipes while I am away at college. I have always been inspired by my mother’s cooking because in it, I see her hard working character, gentleness, and her ability to spread joy so effortlessly through the meals she lovingly makes for our family and others. When I eat Japanese food, I am reminded of the importance of these qualities that my mother possesses, a representation of the values and traditions with which I was raised. In these moments, I see how cooking goes beyond the food itself, having the ability to tell a unique story while simultaneously shaping one’s identity.",
        "contians": ["wheat", "soy"],
        "dietaryRestrictions": "vegetarian",
        "source": "Mom",
        "directions": [
            '01 Heat pan to medium, then add 1 tbsp oil to the pan, and fry the minced ginger until aromatic (about 30 seconds). ',
            '02 Add eggplant into the pan covered and stirring occasionally, until it begins to soften (about 6-8 minutes). ',
            '03 Transfer cooked eggplant and ginger mix onto a separate plate to the side. In the same pan, add 1⁄2 tsp cooking oil, then saute green peppers for 2-3 minutes. ',
            '04 Add back the eggplant and ginger mixture into the pan. Stir occasionally so it doesn’t stick to the bottom for 2 minutes. ',
            '05 Meanwhile, in a small bowl combine miso, brown sugar, dashi, mirin, and mix well. ',
            '06 Set heat to low, and add sauce to the pan, and mix well for about 2 minutes, then turn off heat. ',
            '07 Add 1⁄4 tsp sesame oil, and mix well. ',
            '08 Optional: Add red pepper flakes to preferred spice level. Sprinkle chopped green onion and sesame seeds before serving. Serve warm with Japanese sticky rice.'
          ],
          "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 9,
        "name" : "Chinese Donuts",
        "author": "Sophia Zhang",
        "authorTitle": "Interdisciplinary Art, BA, 2022",
        "prepTime": "3 hours",
        "cookTime": "30 minutes",
        "servingSize": "1 donut",
        "yields": "6 servings",
        "ingredients": [
            "4 cups flour",
            "1 tsp baking soda",
            "1 tsp baking powder 1 tsp salt",
            "1 egg",
            "1 tsp oil",
            "Cold water as needed",
            "Oil for frying"
        ],
        "dippingSauce": "",
        "story" : "Breakfast foods have been important for my family. If you’ve ever traveled to Northern China, you would’ve tried the Chinese donuts (“you tiao”) with soy milk for breakfast. It’s a very famous and cheap street food, but can also be made at home. For my family, a typical breakfast would be different types of porridge along with either sweet pastries or simple salty Chinese donuts. The name “you tiao” literally translates to an “oily stick,” and that is exactly what it is – a fried stick of dough. My grandma would always make it for us either the night before or if she gets up early enough to fry them. It is definitely one of the most delicious home foods that I miss.",
        "contians": ["wheat", "eggs"],
        "dietaryRestrictions": "vegetarian",
        "source": "Grandma",
        "directions": [
            '01 Mix all the dry ingredients together ',
            '02 Mix the dry and wet ingredients together, and add an adequate amount of cold water as mixing the dough ',
            '03 Use the punching method for mixing and forming the dough. The dough should be sticky but not sticky enough to stick to hands. ',
            '04 When the dough is formed, put it in plastic wrap and refrigerate overnight (or 4 hours if you’re running low on time). ',
            '05 Take out the dough and make them into small round pieces that are about the size of a table tennis ball. ',
            '06 Pour an appropriate amount of oil in pan and heat oil with low to medium heat (the oil should be enough to cover the top of the dough). ',
            '07 Take two dough balls, put them together side by side and stretch them. The dough should look like thick, long chopsticks that are stuck together. ',
            '08 Make sure the oil is not too hot so the dough doesn’t burn. Fry the dough. Make sure to flip it constantly to avoid burning. ',
            '09 Repeat steps 7 to 8 until you use all the dough.'
          ],
          "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 10,
        "name" : "Sauteed Water Spinach with Garlic",
        "author": "Thu Thu May Oo",
        "authorTitle": "Customer Service Coordinator, Alumni & Stakeholder Engagement Medical Anthropology & Global Health, BA, 2019",
        "prepTime": "10 minutes",
        "cookTime": "5 minutes",
        "servingSize": "1 cup",
        "yields": "2 servings",
        "ingredients": [
            "1 lb water spinach (ong choy)",
            "3-4 tsp vegetable oil (canola oil or peanut oil is preferred)",
            "3 cloves of garlic, minced",
            "1 tbsp sweet soy sauce (Kwong Hung Seng sauce)",
            "2 tsp chicken or vegetable bouillon powder",
            "2 tsp water",
            "Salt and pepper to taste"
        ],
        "dippingSauce": "",
        "story" : "I find myself a sense of belonging through love and devotion one puts into the making of food. I was born and raised in Burma (Myanmar), and despite living in the US for a decade whilst my family is in Burma, the hardest challenge still is not being able to enjoy my mama’s simple home-cooked meal: the sauteed water spinach with garlic. I still remember vividly how my siblings and I would fight over who got to eat the savory leaves portion of a dish or the crunchy stalks of this nutritious leafy vegetable, which sometimes naturally grew in our backyard. This simple dish makes me realize what it is like to belong in a place where you can share your favorite things and make inedible memories with your beloved ones. What’s more, my passion for cooking grows even stronger as I learn my mama’s recipes to cook and find myself a sense of home away from home.",
        "contians": ["wheat", "soy"],
        "dietaryRestrictions": "vegetarian",
        "source": "Mom",
        "directions": [
            '01 Cut and remove the bottom parts of the spinach stems until you are left with younger and crunchier stems. Then, cut spinach into 3-inch pieces and separate the leaf and thin stems from wider and crunchier parts. Wash well and drain. ',
            '02 Heat a large wok pan to a medium-high heat. Then, add 3-4 teaspoons of vegetable oil in the pan. ',
            '03 Add minced garlic and cook for a few seconds until fragrant. ',
            '04 Add the wider and crunchier stems into the pan first. Add a dash of salt and cook until they are halfway done. Then, add the remaining spinach. ',
            '05 Add all the seasoning including sweet soy sauce, chicken or vegetable bouillon powder, and sprinkle salt and pepper to taste. ',
            '06 Stir constantly for 3-4 minutes until they glisten and are thoroughly cooked. Add water as needed.'
          ],
          "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 11,
        "name" : "Baked Shrimp Toast",
        "author": "Lynda Pham",
        "authorTitle": "Computer Science, BS, 2022",
        "prepTime": "15 minutes",
        "cookTime": "10 minutes",
        "servingSize": "3 toasts",
        "yields": "4 servings",
        "ingredients": [
            "12 large shrimp",
            "2-3 cloves of garlic, finely minced 1⁄2 cup mayonnaise",
            "1⁄4 tsp onion powder",
            "Salt and pepper to taste",
            "1 baguette",
            "1⁄4 cup mozzarella (optional)"
        ],
        "dippingSauce": "",
        "story" : "Growing up, there has always been a dichotomy in the food at family functions. We would serve hot pot for our Vietnamese Thanksgiving and go all-out American for Christmas. My young cousins would only eat the reluctantly-ordered Costco pizza and leave the Vietnamese platters untouched. The only thing that would make my cousins race downstairs is this shrimp toast! The last time we hosted a party, my mom asked me to help her get ready, and I realized how easy it is to make. This recipe is a great way to introduce someone to a non-traditional Vietnamese dish.",
        "contians": ["milk", "eggs", "shellfish", "wheat"],
        "dietaryRestrictions": "",
        "source": "adapted recipe",
        "directions": [
            '01 Preheat oven to 400°F. Line baking sheet with parchment paper or spray it with non-stick oil. ',
            '02 If working with pre-cooked shrimp, slice shrimp into bite-sized pieces. If using raw shrimps, cook peeled shrimps in about a tbsp of vegetable oil. Season with salt and pepper to taste. Cook for approximately 2 minutes on each side or until the shrimps have curled up and turned pink. Slice shrimp after cooking. ',
            '03 Cut baguette into 1-cm thick slices. ',
            '04 In a bowl, mix the garlic, shrimp, mayonnaise, sour, onion powder, and if desired, cheese. ',
            '05 Spread the mixture onto the baguette slices. Add salt and pepper to taste. Bake for 6-7 minutes, or until golden.'
          ],
          "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 12,
        "name" : "Tahini Dip",
        "author": "Danny Arguetty",
        "authorTitle": "Mindfulness Manager, UW Recreation",
        "prepTime": "5 minutes",
        "cookTime": "5 minutes",
        "servingSize": "3 Tbsp",
        "yields": "8 servings",
        "ingredients": [
            "2-3 garlic cloves, peeled 1 cup tahini paste",
            "Juice of 1⁄2 lemon",
            "1 tbsp sea salt",
            "1 whole bunch of parsley, destemmed",
            "2 tbsp olive oil",
            "Water"
        ],
        "dippingSauce": "",
        "story" : "Growing up, every Saturday my family would gather at my Grandma’s apartment for a delectable home-cooked meal. Flavors, colors, card games, and heated political conversations constructed the minutes and hours of this weekly ritual. It was only in my late 20’s that I realized what a special time this was and how blessed I was to have been exposed to so many diverse and delectable dishes. One that always stood out was the tahini dip --so rich and creamy, with each individual ingredient (garlic, lemon, olive oil, sea salt, parsley, sesame) visiting my taste buds and leaving a little moment of delight. Tahini is originally an Arab food adopted by Israelis (where I am from). It not only reminds me of nourishing family time, but also the ways in which food can bridge the gap of difference and hate to help us remember all that we share in common.",
        "contians": [],
        "dietaryRestrictions": "vegan",
        "source": "Self-made",
        "directions": [
            '01 Peel garlic cloves, and blend in a food processor. ',
            '02 Add all other ingredients. ',
            '03 Turn food processor on and slowly add water until desired consistency. ',
            '04 Taste and adjust flavor (some like it more lemony, some more salty). ',
            "05 If you don't have a food processor, use a blender. If you don't have a blender use a jar. Mince the garlic and parsley so they are very small. Put all ingredients in a jar and shake until desired consistency (again here add water and adjust the flavor profile)."
          ],
          "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 13,
        "name" : "Lefse",
        "author": "Cheryl Wheeler",
        "authorTitle": "Program Director, International Specialized Programs",
        "prepTime": "40 minutes",
        "cookTime": "15 minutes",
        "servingSize": "1 piece",
        "yields": "10 servings",
        "ingredients": [
            "2 cups instant potato flakes",
            "2 1⁄2 cups all-purpose flour",
            "1⁄2 cup white whole-wheat flour",
            "1 tsp kosher salt",
            "2 tsp white sugar",
            "2 cups water",
            "1⁄4 cup salted butter, softened",
            "2/3 cup whole milk, room temperature"
        ],
        "dippingSauce": "",
        "story" : "I don’t know how lefse escaped my awareness until I made a 2019 family visit to Norway to explore my distant ancestral roots. I was never especially interested in visiting Scandinavia until my 40s, but I have been very interested in cooking since I was a child. It was eye-opening to “discover” a bread from my own heritage, even when I spend quite a lot of my free time researching and testing bread recipes. For me, lefse represents how all people make incredibly delicious food with whatever they happen to have on hand. After making lefse in Norway, I came back to the US and put my personal touch on this particular recipe by making it partially whole wheat. If you don’t like this vaguely healthy improvement, please use only all-purpose flour. If you are Norwegian and you find fault with my non- traditional whole wheat approach, please send me your passport, altered such that it is now my passport. Thanks!",
        "contians": ["wheat", "milk"],
        "dietaryRestrictions": "vegetarian",
        "source": "Friends",
        "directions": [
            "01 Mix potato flakes, flours, salt and sugar together in a large bowl. ",
            "02 Boil water. Mix water, butter, and milk and combine with dry ingredients. Stir vigorously with a heavy spoon until combined. ",
            "03 Gently knead dough mixture by hand a few times, to form a soft, smooth dough. ",
            "04 Cover and rest dough for at least 30 minutes. If refrigerated, let dough warm up to room temperature for 30-45 minutes prior to the following step. ",
            "05 Weigh the dough and divide it into 10 equal pieces. Pat or roll each piece into a 10-12 inch disc on a very well-floured surface. I like to make them thin and delicate, but you can make them heftier if you already know you prefer a heftier potato-based product. I have never actually used a rolling pin to roll them. But I am sure a more patient person would. ",
            "06 While you are rolling, heat a cast iron skillet, griddle, or a non-stick frying pan. You want it heated to high (400-425°F) and entirely ungreased. I use a large pancake griddle to make the process go more quickly. ",
            "07 Dust flour off the disc as best you can--I use a pastry brush. Using your trusty bench scraper as needed and your dexterous digits, lift the dough disc from the work surface and put on the hot pan. It’s OK to push it around with your fingertips to spread it out a wee bit more at this point if you need to. It will brown in spots, quickly. ",
            "08 Flip it over and cook the other side until nicely spotty, too. Repeat this process. ",
            "09 As you finish the bread, stack them up on a plate covered with a thin kitchen towel (this keeps them extra soft). When all are complete, consume thoughtfully, and strictly in the presence of others to avoid inhaling the entire batch! ",
            "10 Wait, did you ask how to consume them? Lefse can be used as a flatbread, tortilla, or some other kind of wrap. In Norway, I was told they are used to wrap hotdogs, but I think they make a nice wrap for whatever savory leftovers you have around. When I was on my trip, I used them to make grilled cheese “sandwiches” with slices of fresh zucchini in between. You can easily go super sweet with these and eat like pancakes by adding sugar, butter, and cinnamon. I also like the idea of squishing on some sweet items (Norwegian brown cheese and cloudberry jam, eh?), then roll up jelly roll style and tuck away in your backpack in anticipation of hungrier times of travel."
        ],
        "category": "appetizers, sides, and snacks"
    },
    {   
        "id": 14,
        "name" : "Summertime Salad",
        "author": "Lauren Iversen",
        "authorTitle": "Landscape Architecture, MLA, 2020",
        "prepTime": "15 minutes",
        "cookTime": "",
        "servingSize": "2 cups",
        "yields": "6 servings",
        "ingredients": [
            "4-5 garden grown tomatoes",
            "1 garden grown onion",
            "1 garden grown cucumber",
            "Fresh vegetables",
            "Salt and pepper to taste",
            "Olive oil to taste",
            "Balsamic vinegar to taste"
        ],
        "dippingSauce": "",
        "story" : "The Midwest may be known for hearty casseroles and food-on-a-stick (just google food from the Iowa State Fair), but one recipe that reminds me of my childhood in Iowa and Missouri was quite a bit healthier and always for dinner in the late summer. As the long hot days drenched the garden in bright sun, the garden tomato vines would start to explode with dripping- down-your-chin, juicy Beefstakes and Romas. We celebrated the harvest with a simple recipe, to be eaten on the back porch, as the humidity of the day finally subsides. Take the tomatoes and anything growing in your garden, and throw them in a bowl with salt and pepper. Pair it with locally grown peaches-and-cream corn and Iowa pork chop, and dinner is ready. I can practically see the sun setting over the corn tassels as I imagine the dinner now.",
        "contians": [],
        "dietaryRestrictions": "vegan",
        "source": "family",
        "directions": [
            "01 Cut all the vegetables into large chunks. Toss them into a giant salad bowl, then salt and pepper. The olive oil and balsamic vinegar are optional, as the homegrown vegetables are the stars of this bowl."
        ],
        "category": "appetizers, sides, and snacks"
    },
]
    export default recipes;
// {   
//     "id": 1,
//     "name" : "",
//     "author": "",
//     "authorTitle": "",
//     "prepTime": "",
//     "cookTime": "",
//     "servingSize": "",
//     "yields": "",
//     "ingredients": [],
//     "dippingSauce": "",
//     "story" : "",
//     "contians": [],
//     "dietaryRestrictions": "",
//     "source": "",
//     "directions": [],
//     "category": "hearty mains"
// },